{% set name = "pyportfolioopt" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyportfolioopt-{{ version }}.tar.gz
  sha256: 6e52ff150a6ec401c0b329bd344b3e2eacb419c927500279eb11307467f00513

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - cvxpy >=1.1.10,<2
    - cvxopt >=1.2,<2.0
    - numpy >=1.12,<2.0
    - pandas >=0.19
    - scipy >=1.3,<2.0
  run_constrained:
    - matplotlib-base >=3.5.2,<4.0
    - scikit-learn >=1.1.1

test:
  imports:
    - pypfopt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robertmartin8/PyPortfolioOpt
  summary: Financial portfolio optimization in python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - atrawog
