{% set name = "pyportfolioopt" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyportfolioopt-{{ version }}.tar.gz
  sha256: 371ade1fed1deeea7042ba3178b3cf9aac9cd0b1700e949cab8a8c2e72e5566a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.11
  run:
    - python >=3.6,<3.11
    - cvxpy >=1.1.19,<2
    - cvxopt >=1.2,<2
    - numpy >=1.22,<2
    - pandas >=0.19
    - scipy >=1.3,<2
  run_constrained:
    - matplotlib-base >=3.2,<4
    - scikit-learn >=0.24,<2

test:
  imports:
    - pypfopt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robertmartin8/PyPortfolioOpt
  summary: Financial portfolio optimization in python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timkpaine
    - atrawog
