{% set name = "pyportfolioopt" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyportfolioopt-{{ version }}.tar.gz
  sha256: 7e94f41c84fb5865c7a64de995a3ba580188f3ba494f6dfbc02721b5de323f6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6
    - cvxpy >=1.1.19,<2
    - cvxopt >=1.2,<2
    - numpy >=1.22,<2
    - pandas >=0.19
    - scipy >=1.3,<2
  run_constrained:
    - matplotlib-base >=3.2,<4
    - scikit-learn >=0.24,<2

test:
  imports:
    - pypfopt
  # commands:
  #  - pip check
  # requires:
  #  - pip

about:
  home: https://github.com/robertmartin8/PyPortfolioOpt
  summary: Financial portfolio optimization in python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timkpaine
    - atrawog
